{
  try {
    return doGet(null);
  }
 catch (  TimeoutException e) {
    throw new AssertionError(e);
  }
}
